# Generated by Django 4.1 on 2022-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/assets/img/noprofile.jpg', null=True, upload_to='media/pic'),
        ),
    ]
